/**
 * This file was generated by Anchor.
 * DO NOT EDIT - manually update this file with your own changes.
 */

import * as web3 from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";

export type LendingProtocol = {
  version: string;
  name: string;
  instructions: LendingProtocolInstruction[];
  accounts: [LendingProtocolAccount];
  errors: [LendingProtocolError];
  metadata: LendingProtocolMetadata;
};

export type LendingProtocolInstruction = {
  name: string;
  accounts: Account[];
  args: Arg[];
};

export type Account = {
  name: string;
  isMut: boolean;
  isSigner: boolean;
  isOptional: boolean;
  pda?: Pda;
};

export type Pda = {
  seeds: Seed[];
};

export type Seed = {
  type: string;
  path: string;
};

export type Arg = {
  name: string;
  type: string;
};

export type LendingProtocolAccount = {
  name: string;
  type: AccountType;
};

export type AccountType = {
  kind: string;
  fields?: Field[];
};

export type Field = {
  name: string;
  type: string;
};

export type LendingProtocolError = {
  code: number;
  name: string;
  msg: string;
};

export type LendingProtocolMetadata = {
  address: string;
  origin: string;
  binary: string;
  version: string;
  splTokenDecimals: number;
  identifier: string;
};

// === Account Types ===

export interface Bank {
  authority: web3.PublicKey;
  mintAddress: web3.PublicKey;
  totalDeposits: anchor.BN;
  totalDepositShares: anchor.BN;
  totalBorrowed: anchor.BN;
  totalBorrowedShares: anchor.BN;
  liquidationThreshold: anchor.BN;
  liquidationBonus: anchor.BN;
  liquidationCloseFactor: anchor.BN;
  maxLtv: anchor.BN;
  lastUpdated: anchor.BN;
  interestRate: anchor.BN;
}

export interface User {
  owner: web3.PublicKey;
  depositedSol: anchor.BN;
  depositedSolShares: anchor.BN;
  borrowedSol: anchor.BN;
  borrowedSolShares: anchor.BN;
  depositedUsdc: anchor.BN;
  depositedUsdcShares: anchor.BN;
  borrowedUsdc: anchor.BN;
  borrowedUsdcShares: anchor.BN;
  usdcAddress: web3.PublicKey;
  healthFactor: anchor.BN;
  lastUpdated: anchor.BN;
}

// === Instruction Args ===

export interface InitBankArgs {
  liquidationThreshold: anchor.BN;
  maxLtv: anchor.BN;
}

export interface InitUserArgs {
  usdcAddress: web3.PublicKey;
}

export interface DepositArgs {
  amount: anchor.BN;
}

export interface WithdrawArgs {
  amount: anchor.BN;
}

export interface BorrowArgs {
  amount: anchor.BN;
}

export interface RepayArgs {
  amount: anchor.BN;
}

export interface LiquidateArgs {}

// === Instruction Accounts ===

export interface InitBankAccounts {
  signer: web3.PublicKey;
  mint: web3.PublicKey;
  bank: web3.PublicKey;
  bankTokenAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

export interface InitUserAccounts {
  signer: web3.PublicKey;
  userAccount: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

export interface DepositAccounts {
  signer: web3.PublicKey;
  mint: web3.PublicKey;
  bank: web3.PublicKey;
  bankTokenAccount: web3.PublicKey;
  userAccount: web3.PublicKey;
  userTokenAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
}

export interface WithdrawAccounts {
  signer: web3.PublicKey;
  mint: web3.PublicKey;
  bank: web3.PublicKey;
  bankTokenAccount: web3.PublicKey;
  userAccount: web3.PublicKey;
  userTokenAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

export interface BorrowAccounts {
  signer: web3.PublicKey;
  mint: web3.PublicKey;
  bank: web3.PublicKey;
  bankTokenAccount: web3.PublicKey;
  userAccount: web3.PublicKey;
  userTokenAccount: web3.PublicKey;
  solPriceAccount: web3.PublicKey;
  usdcPriceAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

export interface RepayAccounts {
  signer: web3.PublicKey;
  mint: web3.PublicKey;
  bank: web3.PublicKey;
  bankTokenAccount: web3.PublicKey;
  userAccount: web3.PublicKey;
  userTokenAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

export interface LiquidateAccounts {
  liquidator: web3.PublicKey;
  collateralMint: web3.PublicKey;
  borrowedMint: web3.PublicKey;
  collateralBank: web3.PublicKey;
  collateralBankTokenAccount: web3.PublicKey;
  borrowedBank: web3.PublicKey;
  borrowedBankTokenAccount: web3.PublicKey;
  liquidatorCollateralAccount: web3.PublicKey;
  liquidatorBorrowedAccount: web3.PublicKey;
  borrower: web3.PublicKey;
  borrowerAccount: web3.PublicKey;
  solPriceAccount: web3.PublicKey;
  usdcPriceAccount: web3.PublicKey;
  tokenProgram: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram: web3.PublicKey;
}

// === Program ID ===
export const LENDING_PROTOCOL_PROGRAM_ID = new web3.PublicKey(
  "2NYVrByVMmi9BCTZox2QH2v92mfuD8Bg77gmg7Y2kSZ9"
);
